licenses:
  - name: SPSS
    type: lsmon
    license_server: ucolic01.ctx.uco.es
    features_to_include: 1200
    monitor_users: True
    monitor_reservations: False
config:
  port: 8000
  sleep: 60
  lsmon_cmd: ./lsmon
  lmutil_cmd: ./lmutil lmstat -a -c
  rlmutil_cmd: ./rlmutil rlmstat -a -c