---
licenses:
  - name: TESTLAB
    type: rlmutil
    license_server: 27500@ucolic02.ctx.uco.es
    rlm_item_label: v14.0,v17.0,v18.0
    rlm_count_label: "count:"
    features_to_include: ALL
    monitor_users: True
    monitor_reservations: False
config:
  port: 8000
  sleep: 15
  lsmon_cmd: .\lsmon
  lmutil_cmd: .\lmutil lmstat -a -c
  rlmutil_cmd: .\rlmutil rlmstat -a -c
