licenses:
  - name: HYDRUS
    type: web
    license_server: ucolic03.ctx.uco.es
    prefix_url: "http://ucolic03.ctx.uco.es:1947/_int_/features.html"
    suffix_url: ""
    max_url_param: 0
    used_as_free: False
    match_exist: (?:<h2>Current usage of )(?P<featureName>.+?)(?:<\/h2>)
    match_total: "(?:<h4>Total resources: )(?P<featureCount>.+?)(?:<\/h4><\/div>)"
    match_used: "(?:<h4>Resources available: )(?P<featureCount>.+?)(?:<\/h4><\/div>)"
config:
  port: 8000
  sleep: 60
  lsmon_cmd: ./lsmon
  lmutil_cmd: ./lmutil lmstat -a -c
  rlmutil_cmd: ./rlmutil rlmstat -a -c