onlythis:
licenses:
  - name: MATLAB R2018b
    type: lmutil
    skip: False
    license_server: 27002@ucolic01.ctx.uco.es
    features:
      include: ALL
    users:
      monitor: True
  - name: SOLID EDGE
    type: lmutil
    skip: False
    license_server: 28000@ucolic03.ctx.uco.es
    features:
      include: ALL
    users:
      monitor: True
  - name: COMSOL
    type: lmutil
    skip: False
    license_server: 1718@ucolic01.ctx.uco.es
    features:
      include: COMSOLCKL,ELECTROCHEMISTRYCKL,COMSOLGUICKL
    users:
      monitor: True
  - name: MATLAB CAMPUS
    type: lmutil
    skip: False
    license_server: 27001@ucolic03.ctx.uco.es
    features:
      include: ALL
    users:
      monitor: True
  - name: MATHCAD
    type: lmutil
    skip: True
    license_server: 7788@ucolic01.ctx.uco.es
    features:
      include: MATHCAD,254,255,256,257
    users:
      monitor: True
  - name: AUTODESK
    type: lmutil
    skip: False
    license_server: 27001@ucolic02.ctx.uco.es
    features:
      include: ALL
      translate:
          at_stage: 1
          search: ^\d{5}(?P<feature_name>[A-Z0-9\_]+)_(?P<feature_suffix>\d{4})
          translations:
            AMECH_PP: Autocad Mechanical
            RECAP: Autodesk RECAP
            RVT: Autodesk Revit
            REVIT: Autodesk Revit
            RVTMPB: Autodesk Revit MEP
            REVITST: Autodesk Revit Structure
            CIV3D: Autocad Civil 3D
            C3DGO: Autodesk Grading Optimization
    users:
      monitor: True
  - name: ORIGIN2018
    type: lmutil
    skip: False
    license_server: 27002@ucolic02.ctx.uco.es
    features:
      include: OriginPro
    users:
      monitor: True
  - name: ANSYS
    type: lmutil
    skip: False
    license_server: 1055@ucolic03.ctx.uco.es
    features:
      include: ALL
    users:
      monitor: True
  - name: CHEMCAD
    type: lsmon
    skip: False
    license_server: ucolic01.ctx.uco.es
    features:
      include: __CC-B,__CC-D,__CC-SEAT,__CC-SS,__CC-T
    users:
      monitor: True
  - name: SPSS
    type: lsmon
    skip: False
    license_server: ucolic01.ctx.uco.es
    features:
      include: 1200
      translate:
        at_stage: 2
        search: ^(?P<feature_name>[0-9]+)(?P<feature_suffix>)
        translations:
          '1200250': SPSS Version 25
          '1200280': SPSS Version 28
    users:
      monitor: True
  - name: SAP2000
    type: lsmon
    skip: False
    license_server: ucolic03.ctx.uco.es
    features:
      include: SAPUL
    users:
      monitor: True
  - name: GRAPHER
    type: lsmon
    skip: False
    license_server: ucolic01.ctx.uco.es
    features:
      include: Grapher
    users:
      monitor: True
  - name: ACAD2019-CIV3D
    type: lmutil
    skip: True
    license_server: 27000@ucolic01.ctx.uco.es
    features:
      include: 87624C3DGO_2022_0F
    users:
      monitor: True
  - name: PALISADE
    type: lmutil
    skip: False
    license_server: 28000@ucolic02.ctx.uco.es
    features:
      include: Palisade_Network,DecisionTools80_Industrial
    users:
      monitor: True
  - name: SOLIDWORKS
    type: lmutil
    skip: False
    license_server: 25734@ucolic01.ctx.uco.es
    features:
      include: ALL
    users:
      monitor: True
  - name: HYDRUS
    type: webtablejs
    skip: False
    used_as_free: False
    license_server: ucolic03.ctx.uco.es
    features:
      include: 22,26
      url:
        prefix: "http://ucolic03.ctx.uco.es:1947/_int_/features.html"
        suffix: ""
        index: null
      js:
        iloc: 0
        id: mydata
        attr: innerHTML
      label:
        name: Feature
        total: Limit
        used: Sessions
    users:
      monitor: True
      js:
        id: mydata
        attr: innerHTML
        iloc: 0
      url:
        prefix: "http://ucolic03.ctx.uco.es:1947/_int_/sessions.html"
        suffix: null
        index: 1
      table:
        skip_header: null
        method: search
      label:
        featurename: Feature
        hostname: Machine
        username: User
        date: "Login\xA0Time"

  - name: TRIMBLE
    type: webtablejs
    skip: False
    used_as_free: False
    license_server: ucolic03.ctx.uco.es
    product:
      include: 1202
      label: Product
    features:
      include: ALL
      url:
        prefix: "http://ucolic03.ctx.uco.es:1947/_int_/features.html"
        suffix: ""
        index: null
      js:
        iloc: 0
        id: mydata
        attr: innerHTML
      label:
        name: Feature
        total: Limit
        used: Sessions
    users:
      monitor: True
      js:
        id: mydata
        attr: innerHTML
        iloc: 0
      url:
        prefix: "http://ucolic03.ctx.uco.es:1947/_int_/sessions.html"
        suffix: null
        index: 1
      table:
        skip_header: null
        method: search
      label:
        featurename: Feature
        hostname: Machine
        username: User
        date: "Login\xA0Time"

  - name: NVIDIAGRID
    type: webtable
    skip: False
    used_as_free: True
    license_server: ucolic01.ctx.uco.es
    features:
      include: Quadro-Virtual-DWS,GRID-Virtual-Apps
      url:
        prefix: "http://ucolic01.ctx.uco.es:8080/licserver/manageFeatureUsage_view.action;jsessionid=FAC0E15E15CEFDC8C40971B198ED33B0?page=1"
        suffix: ""
        index: null
      table:
        index: 9
      label:
        name: "Feature"
        total: "Count"
        used: "Available"
    users:
      monitor: True
      url:
        prefix: "http://ucolic01.ctx.uco.es:8080/licserver/manageFeatureUsage_featureDetails.action?feature.featureId="
        suffix: "&page1"
        index: 1,2
      table:
        skip_header: 0
        method: index
        index: 3
      label:
        featurename: null
        username: 0
        hostname: 3
        date: 5

  - name: ROBOTSTUDIO
    type: web
    skip: False
    used_as_free: True
    license_server: ucolic02.ctx.uco.es
    features:
      url:
        prefix: "http://ucolic02.ctx.uco.es:2468/Web/Usage/For/RobotStudio/7.x"
        suffix: ""
        index: null
      match:
        exist: (?:<h2>Current usage of )(?P<featureName>.+?)(?:<\/h2>)
        total: "(?:<h4>Total resources: )(?P<featureCount>.+?)(?:<\/h4><\/div>)"
        used: "(?:<h4>Resources available: )(?P<featureCount>.+?)(?:<\/h4><\/div>)"

  - name: TESTLAB
    type: rlmutil
    skip: False
    license_server: 27500@ucolic02.ctx.uco.es
    label:
      item: v14.0,v17.0,v18.0
      count: "count:"
    features:
      include: ALL
    users:
      monitor: True
    monitor_reservations: False
  - name: AUTOSIM
    type: rawsocket
    skip: False
    license_server: ucolic02.ctx.uco.es
    license_port: 5000
    timeout: 3
    recv_bytes: 10
  - name: PRESTO
    type: rawsocket
    skip: False
    license_server: 192.168.115.73
    license_port: 5001
    timeout: 3
    recv_bytes: 10
    connect_only: True
  - name: DEFORM
    type: rawsocket
    skip: False
    license_server: ucolic03.ctx.uco.es
    license_port: 34445
    timeout: 3
    recv_bytes: 10
    connect_only: True
config:
  port: 8000
  sleep: 15
  lsmon_cmd: ./lsmon
  lmutil_cmd: ./lmutil lmstat -a -c
  rlmutil_cmd: ./rlmutil rlmstat -a -c
  webdriver:
    type: remote
    private-url:  "http://sysdocker3.priv.uco.es:4444/wd/hub"
    public-url:  "http://sysdocker3.priv.uco.es:4444/wd/hub"